shared:
  # Rules applicable to both queueing and merge requests.
  compulsory: &compulsory

    # Ensure the minimal CI checks have passed.
    - check-success=DCO
    - check-success=Build (amd64)

    # Ensure we're targetting the default branch.
    - base=main

    # Ensure we have adequete reviews.
    - "#approved-reviews-by>=1"
    - "#changes-requested-reviews-by=0"

    # Ensure we aren't being explicitly blocked with a label.
    - label!=do-not-merge

queue_rules:
  - name: default
    conditions:
      - and: *compulsory

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - and: *compulsory

      # Ensure the review is opted in using labels.
      - label=ready-to-merge

    actions:
      queue:
        method: merge
        name: default
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}
